name: rebuild-snippets

on:
  # Whenever there is a new `ditto` release and, with it, an update of the `releases.json` file.
  repository_dispatch:
    types: ['new-ditto-release']
  workflow_dispatch:

jobs:
  create-pull-request:
    name: Update snippets 
    runs-on: ubuntu-latest
    environment: rebuild-snippets
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: wget
        uses: wei/wget@v1
        with:
          args: -qO- https://software.ditto.live/releases/snippets.json > snippets.json
      - name: "Add snippets" 
        env:
          USE_SSH: true
          GIT_USER: git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-actions"
          git add snippets.json
          git commit -m "[AUTO] Update snippets"
          git reset
          git stash
      - name: Run the Action
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          add_timestamp: true
          commit_prefix: "[AUTO]"
          commit_message: "Updating snippets"
          force: false
          target_branch: update-snippets
      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GH_PAT }}
          target_branch: main
          title: Update Snippets
          body: "**Automated pull request**"
          reviewer: okdistribute
          assignee: okdistribute
          draft: false
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
